[package]
name = "move-vm-in-cosmos"
version = "0.0.1"
authors = ["Dm. Yakushev <dmitryyakushev@wings.ai>"]
edition = "2018"

build = "src/build.rs"

[dependencies]
move-lang = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
libra-crypto = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
vm-runtime-types = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
language-e2e-tests = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
vm = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
vm-cache-map = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
vm-runtime = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
libra-state-view = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
libra-config = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
libra-types = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
stdlib = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
bytecode-verifier = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
anyhow = "1.0.25"
lazy_static = "1.4.0"

# TODO: migrate to
# bytes = "0.5.3"
bytes = "0.4"

tonic = "0.1.0-beta.1"
prost = "0.5"
prost-types = "0.5"
tokio = { version = "0.2", features = ["macros"] }

[build-dependencies]
tonic-build = "0.1.0-beta.1"
