[package]
name = "move-vm-in-cosmos"
version = "0.0.1"
authors = ["Dm. Yakushev <dmitryyakushev@wings.ai>"]
edition = "2018"

build = "src/build.rs"

[dependencies]
move-lang = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
libra-crypto = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
vm-runtime-types = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
language-e2e-tests = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
vm = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
vm-cache-map = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
vm-runtime = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
libra-state-view = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
libra-config = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
libra-types = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
stdlib = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
bytecode-verifier = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
lcs = {git = "https://github.com/WingsDao/libra.git", package = "libra-canonical-serialization", branch = "09.01.2020"}
compiler = {git = "https://github.com/WingsDao/libra.git", branch = "09.01.2020"}
anyhow = "1.0.25"
lazy_static = "1.4.0"

# TODO: migrate to
# bytes = "0.5.3"
bytes = "0.4"

tonic = "0.1.0"
prost = "0.6"
prost-types = "0.6"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
futures = "0.3.0"

# cli
structopt = "0.3.7"
http = "0.2.0"

[build-dependencies]
tonic-build = "0.1.0"
