[package]
name = "move-vm-in-cosmos"
version = "0.0.1"
authors = ["Dm. Yakushev <dmitryyakushev@wings.ai>"]
edition = "2018"

build = "build.rs"

[dependencies]
move-lang = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
libra-crypto = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
vm-runtime-types = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
language-e2e-tests = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
vm = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
vm-cache-map = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
vm-runtime = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
libra-state-view = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
libra-config = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
libra-types = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
stdlib = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
bytecode-verifier = {git = "https://github.com/WingsDao/libra.git", branch = "26.12.2019"}
anyhow = "1.0.25"
lazy_static = "1.4.0"

protobuf = "2.8.1"                     # Rust implementation of Google protocol buffers
grpc            = "~0.6"
futures         = "~0.1"
futures-cpupool = "~0.1"
tls-api = "0.2.0"                   # TLS API without implementation

[build-dependencies]
protoc-rust-grpc = "0.6.1"
